//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> ApprovalState { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReceiptNo { get; set; }
        public string Explanation { get; set; }
        public Nullable<bool> IsSentToApproved { get; set; }
        public string ExpenseDetail { get; set; }
    
        public virtual User User { get; set; }
    }
}
